blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 게시글
    path('', views.BlogIndex.as_view(), name='list'),
    path('write/', views.PostWrite.as_view(), name='write'),
    path('<int:post_id>/', views.PostDetail.as_view(), name='detail'),
    path('edit/<int:post_id>/', views.PostUpdate.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.PostDelete.as_view(), name='delete'),
    path('<int:post_id>/like/', views.PostLike.as_view(), name='like'),
    # 코멘트
    path('<int:post_id>/comment/write/', views.CommentWrite.as_view(), name='cm-write'),
    path('comment/delete/<int:comment_id>/', views.CommentDelete.as_view(), name='cm-delete'),
    path('<int:post_id>/<int:comment_id>/like/', views.CommentLike.as_view(), name='cm-like'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .admin_url import ADMIN_URL

urlpatterns = [
    # path('admin/', admin.site.urls),
    path(ADMIN_URL, admin.site.urls),
    path('', views.IndexMain.as_view()),
    path('error/', views.Error.as_view(), name='error'),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password/change/', views.PasswordChange.as_view(), name='pw-change'),
    path('delete/', views.UserDelete.as_view(), name='delete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('profile/update/', views.ProfileUpdate.as_view(), name="pf-update"),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    thumbnail = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    view_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    like_count = models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.title}'


class PostFeeling(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.BooleanField(default=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='child_comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_fixed = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    depth = models.IntegerField(default=1)
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.post.title}/{self.content}'


class CommentFeeling(models.Model):

    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.BooleanField(default=True)


class Tag(models.Model):
    TAG_CHOICES = [
        ('Life', 'Life'),
        ('Style', 'Style'),
        ('Tech', 'Tech'),
        ('Sport', 'Sport'),
        ('Photo', 'Photo'),
        ('Develop', 'Develop'),
        ('Music', 'Music')
    ]
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=10, choices=TAG_CHOICES, null=True, blank=True)

    def __str__(self):
        return f'{self.post.title}/{self.name}'

blog/forms.py
from django import forms
from .models import Post, Comment, Tag

import re

class PostForm(forms.ModelForm):

    tags = forms.MultipleChoiceField(choices=Tag.TAG_CHOICES)

    class Meta:
        model = Post
        fields = ['title', 'tags', 'content', 'thumbnail']

    def is_valid(self):
        valid = super().is_valid()

        if not valid:
            return False

        p = re.compile(r'<script[^>]*>.*?<\/script[^>]*>', re.DOTALL)
        self.cleaned_data['content']= p.sub(' ' , self.cleaned_data['content'])

        return True


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content', 'parent_comment']

blog/views.py
from django.shortcuts import render, redirect
from django.http import Http404

from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

from .models import Post, Comment, Tag, PostFeeling, CommentFeeling
from .forms import PostForm, CommentForm

from myapp.utils.utils import get_banner, view_count_cookie

from django.utils.decorators import method_decorator
from myapp.utils.decorator import is_user_own


# Create your views here.


class BlogIndex(View):
    
    def get(self, request):
        category_name = request.GET.get('category', None)
        page = int(request.GET.get('page', 0))
        sort = request.GET.get('sort', 'reverse')
        tag_list = list(map(lambda x: x[0], Tag.TAG_CHOICES))
        search_option = {
            "search_list" : {
                'normal': '생성시간▲',
                'reverse': '생성시간▼',
            },
            "category_name": category_name,
            "sort_option": sort,
        }

        q = Q(is_deleted=False)

        if category_name and category_name in tag_list:
            q &= Q(tag__name=category_name)
            title = f'{category_name} 검색 결과'
            banner = get_banner(main=f'{category_name} Blog')
        else:
            title = f'블로그에 오신것을 환영합니다.'
            banner = get_banner(main=f'Our Blog')

        if sort == 'normal':
            posts = Post.objects.prefetch_related('tag_set').filter(q).order_by('created_at')
        elif sort == 'reverse':
            posts = Post.objects.prefetch_related('tag_set').filter(q).order_by('-created_at')

        paginator = Paginator(posts, 6)
        try:
            page_object = paginator.page(page)
        except PageNotAnInteger:
            page_object = paginator.page(1)
        except EmptyPage:
            if page <= 0:
                page_object = paginator.page(1)
            else:
                page_object = paginator.page(paginator.num_pages)

        context = {
            "title": title,
            "banner": banner,
            "posts": page_object,
            "max_page": paginator.num_pages,
            "tag_list": tag_list,
            "search_option": search_option,
        }
        return render(request, 'blog/post_list.html', context)


### 포스트
class PostWrite(LoginRequiredMixin, View):

    def get(self, request):
        tag_list = list(map(lambda x: x[0], Tag.TAG_CHOICES))
        context = {
            "title": "게시글 작성하기",
            "banner": get_banner(),
            'tag_list': tag_list,
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            user = request.user
            post = Post.objects.create(
                writer=user,
                title=form.cleaned_data['title'],
                content=form.cleaned_data['content'],
                thumbnail=form.cleaned_data['thumbnail']
                )
            tag_names = form.cleaned_data['tags']
            for tag in tag_names:
                Tag.objects.create(name=tag, post=post)
            return redirect('blog:list')
        messages.error(request, form.errors)
        return redirect('blog:write')


class PostDetail(View):
    
    def get(self, request, post_id):
        try:
            post = Post.objects.prefetch_related('comment_set', 'tag_set', 'postfeeling_set').get(pk=post_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        
        cookie = view_count_cookie(request, post_id)

        if cookie.get('flag'):
            post.view_count += 1
            post.save()
        
        if request.user.is_authenticated:
            user_feeling_post = post.postfeeling_set.filter(user=request.user)
            is_like_post = True if user_feeling_post and user_feeling_post[0].like == True else False
            like_comment_list = Comment.objects.filter(
                post=post,
                commentfeeling__user=request.user,
                commentfeeling__like=True
            ).values_list('pk', flat=True)
        else:
            is_like_post = False
            like_comment_list = []
        
        comments = post.comment_set.filter(depth=1)
        tags = post.tag_set.all()
        
        context = {
            "title": post.title,
            "banner": get_banner(),
            "post": post,
            "comments": comments,
            "tags": tags,
            "is_like_post": is_like_post,
            "like_comment_list": like_comment_list,
        }

        response = render(request, 'blog/post_detail.html', context)
        response.set_cookie('view_count', cookie.get('value'), expires=cookie.get('expire'))

        return response


@method_decorator(is_user_own, 'get')
@method_decorator(is_user_own, 'post')
class PostUpdate(LoginRequiredMixin, View):

    def get(self, request, post_id):
        try:
            post = Post.objects.prefetch_related('tag_set').get(pk=post_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        tag_list = list(map(lambda x: x[0], Tag.TAG_CHOICES))
        tags = post.tag_set.all()
        selected_tag_list = []
        for tag in tags:
            selected_tag_list.append(tag.name)
        context = {
            "title": f'{post.title} 수정',
            "banner": get_banner(),
            "post": post,
            "tag_list": tag_list,
            "selected_tag_list": selected_tag_list,
        }
        return render(request, 'blog/post_edit.html', context)

    def post(self, request, post_id):
        form = PostForm(request.POST)
        try:
            post = Post.objects.prefetch_related('tag_set').get(pk=post_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.thumbnail = form.cleaned_data['thumbnail']
            post.save()
            update_tags = form.cleaned_data['tags']
            current_tags = post.tag_set.all()
            for tag_name in update_tags:
                Tag.objects.get_or_create(name=tag_name, post_id=post_id)
            for tag in current_tags:
                if tag.name not in update_tags:
                    tag.delete()
            return redirect('blog:detail', post_id = post_id)
        messages.error(request, form.errors)
        return redirect('blog:edit', post_id=post_id)


@method_decorator(is_user_own, 'post')
class PostDelete(LoginRequiredMixin, View):

    def post(self, request, post_id):
        try:
            post = Post.objects.prefetch_related('comment_set', 'tag_set').get(pk=post_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        post.is_deleted = True
        post.save()
        return redirect('blog:list')


class PostLike(LoginRequiredMixin, View):

    def post(self, request, post_id):
        try:
            post = Post.objects.get(pk=post_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        
        user = request.user

        try:
            feeling = PostFeeling.objects.select_related('user').get(post=post, user=user)
            like = feeling.like
            if like:
                post.like_count -= 1
            else:
                post.like_count += 1
            post.save()
            feeling.like = not like
            feeling.save()
        except:
            PostFeeling.objects.create(user=user, post=post)
            post.like_count += 1
            post.save()

        return redirect('blog:detail', post_id=post_id)


### 코멘트
class CommentWrite(LoginRequiredMixin, View):
    
    def post(self, request, post_id):
        form = CommentForm(request.POST)
        if form.is_valid():
            user = request.user
            try:
                post = Post.objects.get(pk=post_id)
            except ObjectDoesNotExist as e:
                raise Http404()
            comment = form.save(commit=False)
            comment.writer = user
            comment.post = post
            if comment.parent_comment:
                comment.depth = comment.parent_comment.depth + 1
            else:
                comment.depth = 1
            comment.save()
        return redirect('blog:detail', post_id=post_id)


@method_decorator(is_user_own, 'post')
class CommentDelete(LoginRequiredMixin, View):

    def post(self, request, comment_id):
        try:
            comment = Comment.objects.get(pk=comment_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        comment.is_deleted = True
        comment.save()
        return redirect('blog:detail', post_id=comment.post.pk)


class CommentLike(LoginRequiredMixin, View):

    def post(self, request, comment_id, post_id):
        try:
            comment = Comment.objects.get(pk=comment_id)
        except ObjectDoesNotExist as e:
            raise Http404()
        
        user = request.user

        try:
            feeling = CommentFeeling.objects.select_related('user').get(comment=comment, user=user)
            like = feeling.like
            if like:
                comment.like_count -= 1
            else:
                comment.like_count += 1
            comment.save()
            feeling.like = not like
            feeling.save()
        except:
            CommentFeeling.objects.create(user=user, comment=comment)
            comment.like_count += 1
            comment.save()

        return redirect('blog:detail', post_id=post_id)

blog/templates/blog/basetemplate.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  
{% endblock head %}
{% block content %}
  
{% endblock content %}
{% block script %}
  
{% endblock script %}

blog/templates/blog/comments.html
{% load static %}
{% for comment in comments %}
  {% if not comment.is_deleted %}
  <div class="comment-content">
    <dl class="comment-author-wrap">
      <dt class="a11y-hidden">Author</dt>
      {% if comment.writer.is_active %}
        <dd class="author"><a href="{% url 'user:profile' user_id=comment.writer.pk %}"><img src="{{ comment.writer.profile.image }}" alt="profile image" />{{ comment.writer }}</a></dd>
      {% else %}
        <dd class="author"><img src="{% static '/images/anonymous.png' %}" alt="" /> 탈퇴한 유저입니다. </dd>
      {% endif %}
      <dt class="a11y-hidden">Created</dt>
      <dd class="created">{{ comment.created_at }}</dd>
    </dl>
    <div class="comment-content-box">
      <p>{{ comment.content }}</p>
      <form action="{% url 'blog:cm-like' post_id=post.pk comment_id=comment.pk %}" method="post">
        {% csrf_token %}
        {% if comment.pk in like_comment_list %}
          <button type="submit" class="btn-like liked">{{ comment.like_count }}</button>
        {% else %}
          <button type="submit" class="btn-like">{{ comment.like_count }}</button>
        {% endif %}
      </form>
    </div>
    <div class="comment-btn-wrap">
      {% if user == comment.writer %}
        <form action="{% url 'blog:cm-delete' comment_id=comment.pk %}" method="post">
          {% csrf_token %}
          <button class="btn-delete">
            <span class="a11y-hidden">delete</span>
          </button>
        </form>
      {% endif %}
      {% if user.is_authenticated %}
        <button class="recomment btn-comment" cm_id="{{comment.pk}}">댓글</button>
        <form action="{% url 'blog:cm-write' post_id=post.pk %}" method="post" class="comment-form no-display" >
          {% csrf_token %}
          <textarea name="content"></textarea>
          <input type="hidden" name="parent_comment" value="{{comment.pk}}">
          <input type="submit" value="작성" class="btn-comment">
          <input type="button" class="recomment-cancel btn-comment" value="취소">
        </form>
      {% endif %}
    </div>
    {% else %}
    <div class="comment-content">
      <dl class="author-wrap">
        <dt class="a11y-hidden">Author</dt>
        <dd class="author"><img src="{% static '/images/anonymous.png' %}" alt="" />-</dd>
        <dt class="a11y-hidden">Created</dt>
        <dd class="created">-</dd>
      </dl>
      <div class="comment-content-box">
        <p class="deleted-comment">삭제된 코멘트 입니다.</p>
      </div>
    {% endif %}
    {% if comment.child_comments %}
      {% with comment.child_comments.all as comments %}
        {% include 'blog/comments.html' %}
      {% endwith %}
    {% endif %}
  </div>
{% endfor %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
  <link rel="stylesheet" href="{% static '/css/view.css' %}" />
  <link rel="stylesheet" href="{% static '/css/detail.css' %}" />
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          {% if not post.is_deleted %}
            <!-- author -->
            <dl class="author-wrap">
              <dt class="a11y-hidden">Author</dt>
              {% if post.writer.is_active %}
                <dd class="author"><a href="{% url 'user:profile' user_id=post.writer.pk %}"><img src="{{ post.writer.profile.image }}" alt="" />{{ post.writer }}</dd></a>
              {% else %}
                <dd class="author"><img src="{% static '/images/anonymous.png' %}" alt="" />탈퇴한 유저입니다.</dd>
              {% endif %}
              <dt class="a11y-hidden">Created</dt>
              <dd class="created">{{ post.created_at }}</dd>
            </dl>
            <!-- //author -->

            <!-- category -->
            <dl class="category">
              <dt class="a11y-hidden">Category</dt>
              {% if tags %}
                {% for tag in tags %}
                  <dd><a href="/blog/?category={{tag.name}}">{{ tag.name }}</a></dd>
                {% endfor %}
              {% else %}
                <dd>no tags</dd>
              {% endif %}
            </dl>
            <!-- //category -->
            <!-- content -->
            <div class="title-wrap">
              <h2>{{ post.title }}</h2>
              <form action="{% url 'blog:like' post_id=post.pk %}" method="post">
                {% csrf_token %}
                {% if is_like_post == True %}
                  <button type="submit" class="btn-like liked">Like {{ post.like_count }}</button>
                {% else %}
                  <button type="submit" class="btn-like">Like {{ post.like_count }}</button>
                {% endif %}
              </form>
            </div>
            <div class="view-wrap">
              <p>조회수: {{ post.view_count }}</p>
            </div>
            <hr />
            <div class="view-contents">
              <p>{{ post.content|safe }}</p>
            </div>
            <!-- //content -->
            <hr />
            <!-- comment -->
            {% if user.is_authenticated %}
                <form action="{% url 'blog:cm-write' post_id=post.pk %}" method="post" class="comment-form">
                  {% csrf_token %}
                  <textarea name="content"></textarea>
                  <input type="submit" value="작성" class="btn-comment">
                </form>
                <hr>
            {% endif %}
            <div class="comment-wrap">
              {% if comments %}
                {% include 'blog/comments.html' %}
              {% else %}
                <div class="comment-content">
                  <div class="comment-content-box">
                    <p>댓글이 없습니다.</p>
                  </div>
                </div>
              {% endif %}
            </div>
            <!-- //comment -->
            {% if user == post.writer %}
              <div class="btn-group">
                <a href="{% url 'blog:edit' post_id=post.pk %}" class="btn-modify">
                  <span class="a11y-hidden">modify</span>
                </a>
                <form action="{% url 'blog:delete' post_id=post.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn-delete">
                    <span class="a11y-hidden">delete</span>
                  </button>
                </form>
              </div>
            {% endif %}
          {% else %}
            <!-- author -->
            <dl class="author-wrap">
              <dt class="a11y-hidden">Author</dt>
              <dd class="author"><img src="{% static '/images/anonymous.png' %}" alt="" />--</dd>
              <dt class="a11y-hidden">Created</dt>
              <dd class="created">--</dd>
            </dl>
            <!-- //author -->
            <!-- content -->
            <div class="title-wrap">
              <h2>삭제된 게시물입니다.</h2>
            </div>
            <hr />
            <div class="view-contents">
              <p>사용자나 관리자에 의해서 삭제된 게시물입니다.</p>
            </div>
            <!-- //content -->
            <hr />
            <a href="{% url 'blog:list' %}" class="button">돌아가기</a>
          {% endif %}
        </div>
      </section>
    </div>
  </div>
  <!-- //post view -->
{% endblock content %}
{% block script %}
  <script src="{% static '/js/comments.js' %}"></script>
{% endblock script %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
  <link rel="stylesheet" href="{% static '/css/view.css' %}" />
  <link rel="stylesheet" href="{% static '/css/post_form.css' %}" />
  <!-- toast editor -->
  <link rel="stylesheet"href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          <div class="title-wrap">
            <h2>게시글 수정하기</h2>
          </div>
          <hr>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <form id="write-form" action="{% url 'blog:edit' post_id=post.pk %}" method="post">
            {% csrf_token %}
            <div class="title-input">
              <label for="form-title">제목</label>
              <input id="form-title" name="title" type="text" value="{{ post.title }}">
            </div>
            <div class="category-drop"><span class="selected-category">
              <dl class="category"><dt class="a11y-hidden">선택된 카테고리</dt>
              {% for tag in selected_tag_list %}
                <dd>{{ tag }}</dd>
              {% endfor %}
              </dl>
            </span><button type="button" class="btn-select">▼</button></div>
            <ul class="select-wrap no-display">
              {% for tag in tag_list %}
                {% if tag in selected_tag_list %}
                  <li>
                    <input type="checkbox" name="tags" id="{{tag}}" value="{{tag}}" checked>
                    <label for="{{tag}}">{{tag}}</label>
                  </li>
                {% else %}
                  <li>
                    <input type="checkbox" name="tags" id="{{tag}}" value="{{tag}}">
                    <label for="{{tag}}">{{tag}}</label>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
            <div id="editor"></div>
            <input id="form-content" name="content" type="hidden">
            <input id="form-thumbnail" name="thumbnail" type="hidden">
            <input class="btn-save" type="submit" value="수정">
          </form>
        </div>
      </section>
    </div>
  </div>
{% endblock content %}
{% block script %}
  <script>
    const post_content = `{{ post.content|safe }}`
  </script>
  <script src="{% static '/js/post_form.js' %}"></script>
{% endblock script %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/post_form.css' %}" />
  <!-- toast editor -->
  <link rel="stylesheet"href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          <div class="title-wrap">
            <h2>게시글 작성하기</h2>
          </div>
          <hr>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <form id="write-form" action="{% url 'blog:write' %}" method="post">
            {% csrf_token %}
            <div class="title-input">
              <label for="form-title">제목</label>
              <input id="form-title" name="title" type="text">
            </div>
            <div class="category-drop"><span class="selected-category">카테고리 선택</span><button type="button" class="btn-select">▼</button></div>
            <ul class="select-wrap no-display">
              {% for tag in tag_list %}
              <li>
                <input type="checkbox" name="tags" id="{{tag}}" value="{{tag}}">
                <label for="{{tag}}">{{tag}}</label>
              </li>
              {% endfor %}
            </ul>
            <div id="editor"></div>
            <input id="form-content" name="content" type="hidden">
            <input id="form-thumbnail" name="thumbnail" type="hidden">
            <input class="btn-save" type="submit" value="작성">
          </form>
        </div>
      </section>
    </div>
  </div>
{% endblock content %}
{% block script %}
  <script>
    const post_content = ""
  </script>
  <script src="{% static '/js/post_form.js' %}"></script>
{% endblock script %}