blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 게시글
    path('', views.BlogIndex.as_view(), name='list'),
    path('write/', views.PostWrite.as_view(), name='write'),
    path('<int:post_id>/', views.PostDetail.as_view(), name='detail'),
    path('edit/<int:post_id>/', views.PostUpdate.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.PostDelete.as_view(), name='delete'),
    path('<int:post_id>/like/', views.PostLike.as_view(), name='like'),
    # 코멘트
    path('<int:post_id>/comment/write/', views.CommentWrite.as_view(), name='cm-write'),
    path('comment/delete/<int:comment_id>/', views.CommentDelete.as_view(), name='cm-delete'),
    path('<int:post_id>/<int:comment_id>/like/', views.CommentLike.as_view(), name='cm-like'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .admin_url import ADMIN_URL

urlpatterns = [
    # path('admin/', admin.site.urls),
    path(ADMIN_URL, admin.site.urls),
    path('', views.IndexMain.as_view()),
    path('error/', views.Error.as_view(), name='error'),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password/change/', views.PasswordChange.as_view(), name='pw-change'),
    path('delete/', views.UserDelete.as_view(), name='delete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('profile/update/', views.ProfileUpdate.as_view(), name="pf-update"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone
from .data import DEFAULT_PROFILE_IMAGE


class UserManager(BaseUserManager):

    def _create_user(self, username, password, nickname, is_staff, is_superuser, **extra_fields):
        if not username:
            raise ValueError('User must have an username')
        now = timezone.localtime()
        user = self.model(
            username = username,
            nickname = nickname,
            is_staff = is_staff,
            is_active = True,
            is_superuser = is_superuser,
            last_login = now,
            date_joined = now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)  
        return user
    
    def create_user(self, username, password, nickname, **extra_fields):
        return self._create_user(username, password, nickname, False, False, **extra_fields)
    
    def create_superuser(self, username, password, nickname, **extra_fields):
        return self._create_user(username, password, nickname, True, True, **extra_fields)


class User(AbstractUser):
    nickname = models.CharField(max_length=15)
    first_name = None
    last_name = None

    REQUIRED_FIELDS = ['nickname']

    objects = UserManager()

    def __str__(self):
        return self.nickname


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.TextField(default='/static/images/profile.jpg')
    state = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.nickname

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.hashers import check_password
from .models import Profile
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'nickname']
        # fields = UserCreationForm.Meta.fields + ('email',)


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileUpdateForm(forms.ModelForm):

    nickname = forms.CharField(max_length=15)

    class Meta:
        model = Profile
        fields = ['image', 'state', 'nickname']


class UserDeleteForm(forms.Form):

    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')

user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist

from myapp.utils.utils import get_banner

from .models import Profile
from .forms import RegisterForm, LoginForm, ProfileUpdateForm, UserDeleteForm
from django.contrib.auth.forms import PasswordChangeForm


User = get_user_model()


### Registration
class Registration(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        form = RegisterForm()
        context = {
            'title': '회원가입',
            'banner': get_banner(main='Join Us'),
            'form': form,
        }
        return render(request, 'user/user_register.html', context)

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile.objects.create(user=user)
            return redirect('user:login')
        context = {
            'title': '회원가입',
            'banner': get_banner(main='Join Us'),
            'form': form,
        }
        return render(request, 'user/user_register.html', context)

### Login
class Login(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        form = LoginForm()

        context = {
            'title': '로그인',
            'banner': get_banner(main='Login Blog'),
            'form': form,
        }
        return render(request, 'user/user_login.html', context)

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        form = LoginForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user:
                login(request, user)
                return redirect('blog:list')
        context = {
            'title': '로그인',
            'banner': get_banner(main='Login Blog'),
            'form': form,
        }
        return render(request, 'user/user_login.html', context)


class Logout(View):

    def get(self, request):
        logout(request)
        return redirect('blog:list')


class PasswordChange(LoginRequiredMixin, View):

    def get(self, request):
        form = PasswordChangeForm(request.user)
        context = {
            'title': '패스워드 변경',
            'banner': get_banner(),
            'form': form,
        }
        return render(request, 'user/password_change.html', context)
    
    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login')
        context = {
            'title': '패스워드 변경',
            'banner': get_banner(),
            'form': form,
            }
        return render(request, 'user/password_change.html', context)


class UserDelete(LoginRequiredMixin, View):

    def get(self, request):
        form = UserDeleteForm(request.user)
        context = {
            'title': '회원 탈퇴',
            'banner': get_banner(),
            'form': form,
            }
        return render(request, 'user/user_delete.html', context)
    
    def post(self, request):
        user = request.user
        form = UserDeleteForm(user, request.POST)
        if form.is_valid():
            user.is_active = False
            user.save()
            logout(request)
            return redirect('blog:list')
        
        context = {
            'title': '회원 탈퇴',
            'banner': get_banner(),
            'form': form,
            }
        return render(request, 'user/user_delete.html', context)


# ### Profile


class ProfileView(View):

    def get(self, request, user_id):
        try:
            profile = Profile.objects.select_related('user').get(user__pk=user_id)
        except ObjectDoesNotExist as e:
            messages.error(request, "해당 유저는 존재하지 않습니다.")
            return redirect('error')
        if not profile.user.is_active:
            messages.error(request, "해당 유저는 존재하지 않습니다.")
            return redirect('error')
        user = profile.user
        context = {
            "title": f"{user.nickname}의 프로필",
            'banner': get_banner(main=f"{user.username}'s Profile"),
            'profile': profile
        }
        return render(request, 'user/user_profile.html', context)


class ProfileUpdate(View):

    def get(self, request):
        user = request.user
        profile = Profile.objects.get(user=user)
        context = {
            "title": f"{user.nickname}의 프로필",
            'banner': get_banner(main=f"{user.username}'s Profile"),
            'profile': profile
        }
        return render(request, 'user/profile_update.html', context)

    def post(self, request):
        form = ProfileUpdateForm(request.POST)
        if form.is_valid():
            user = request.user
            profile = Profile.objects.get(user=user)
            profile.image = form.cleaned_data.get('image')
            profile.state = form.cleaned_data.get('state')
            profile.save()
            user.nickname = form.cleaned_data.get('nickname')
            user.save()
            return redirect('user:profile', user_id=user.pk)

user/templates/user/password_change.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/user_form.css' %}" />
{% endblock head %}

{% block content %}
<div class="view">
  <div class="max-width">
    <section class="wrap-box">
      <div class="inner">
        <div class="title-wrap">
          <h2>비밀번호 변경</h2>
        </div>
        <hr>
        <form class="user-form" action="{% url 'user:pw-change' %}" method="post">
          {% csrf_token %}
          <div class="user-form-wrap">
            <label class="label-width" for="id_old_password">현재 비밀번호</label>
            <p>{{ form.old_password }}</p>
          </div>
          {{ form.errors.old_password }}
          <div class="user-form-wrap">
            <label class="label-width" for="id_new_password1">새 비밀번호</label>
            <p>{{ form.new_password1 }}</p>
          </div>
          {{ form.errors.new_password1 }}
          <div class="user-form-wrap">
            <label class="label-width" for="id_password">새 비밀번호 확인</label>
            <p>{{ form.new_password2 }}</p>
          </div>
          {{ form.errors.new_password2 }}
          <input type="submit" class="button" value="비밀번호 변경">
        </form>

        
    </section>
  </div>
</div>
{% endblock content %}

user/templates/user/profile_update.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
  <link rel="stylesheet" href="{% static '/css/view.css' %}" />
  <link rel="stylesheet" href="{% static '/css/profile.css' %}" />
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          <!-- content -->
          <div class="title-wrap">
            <h2>프로필 수정하기</h2>
          </div>
          <hr />
          <div class="view-contents">
            <!-- form -->
            <form action="{% url 'user:pf-update' %}" method="post" class="profile">
              {% csrf_token %}
              <div class="profile-wrap">
                <label class="label-width" for="nickname">닉네임</label>
                <input type="text" id="nickname" name="nickname" value="{{ user.nickname }}" />
              </div>
              <input type="hidden" name="image" value="{{ profile.image }}" />
              <div class="profile-wrap">
                <label class="label-width" for="get_image">프로필 이미지</label>
                <img class="profile-thumbnail" src="{{ profile.image }}" alt="" />
                <input type="file" accept="image/*" id="get_image">
              </div>
              <div class="profile-wrap">
                <label class="label-width" for="state">상태</label>
                {% if profile.state %}
                  <input type="text" id="state" name="state" value="{{ profile.state }}" placeholder="당신의 상태를 입력해주세요!">
                {% else %}
                  <input type="text" id="state" name="state" value="" placeholder="당신의 상태를 입력해주세요!">
                {% endif %}
              </div>
              <input class="btn-save" type="submit" value="수정">
            </form>
            <!-- //form -->
            <div class="btn-group profile-btns">
              <a href="{% url 'user:pw-change' %}" class="btn-modify">
                비밀번호 변경
              </a>
              <a href="{% url 'user:delete' %}" class="btn-delete">
                회원 탈퇴
              </a>
            </div>
          </div>
          <!-- //content -->
        </div>
      </section>
    </div>
  </div>
  <!-- //post view -->
{% endblock content %}
{% block script %}
<script src="{% static '/js/profile_update.js' %}"></script>
{% endblock script %}

user/templates/user/user_delete.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/user_form.css' %}" />
{% endblock head %}

{% block content %}
<div class="view">
  <div class="max-width">
    <section class="wrap-box">
      <div class="inner">
        <div class="title-wrap">
          <h2>회원 탈퇴</h2>
        </div>
        <hr>
        <p>회원을 탈퇴할 경우 정상적인 활동을 할 수 없습니다.</p>
        <p>복구를 원하실 경우, 이메일로 문의주시길 바랍니다.</p>
        <p>정말로 회원을 탈퇴하고 싶으시다면 비밀번호를 입력하고 회원탈퇴 버튼을 눌러주세요.</p>
        <hr>
        <form class="user-form" action="{% url 'user:delete' %}" method="post">
          {% csrf_token %}
          <div class="user-form-wrap">
            <label class="label-width" for="id_old_password">비밀번호</label>
            <p>{{ form.password }}</p>
          </div>
          {{ form.errors.password }}
          <input type="submit" class="button" value="회원탈퇴">
        </form>

        
    </section>
  </div>
</div>
{% endblock content %}

user/templates/user/user_login.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/user_form.css' %}" />
{% endblock head %}

{% block content %}
<div class="view">
  <div class="max-width">
    <section class="wrap-box">
      <div class="inner">
        <div class="title-wrap">
          <h2>로그인</h2>
        </div>
        <hr>
        <form class="user-form" action="{% url 'user:login' %}" method="post">
          {% csrf_token %}
          <div class="user-form-wrap">
            <label class="label-width" for="id_username">아이디</label>
            <p>{{ form.username }}</p>
          </div>
          <div class="user-form-wrap">
            <label class="label-width" for="id_password">비밀번호</label>
            <p>{{ form.password }}</p>
          </div>
          {{ form.non_field_errors }}
          <input type="submit" class="button" value="로그인">
        </form>
    </section>
  </div>
</div>
{% endblock content %}

user/templates/user/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
  <link rel="stylesheet" href="{% static '/css/view.css' %}" />
  <link rel="stylesheet" href="{% static '/css/profile.css' %}" />
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          <!-- content -->
          <div class="title-wrap">
            <h2>{{ profile.user.username }}님의 프로필</h2>
          </div>
          <hr />
          <div class="view-contents">
            <div class="profile">
              <div class="profile-wrap">
                <p class="label-width">닉네임</p>
                <p>{{ profile.user.nickname }}</p>
              </div>
              <div class="profile-wrap">
                <p class="label-width">프로필 이미지</p>
                <p><img class="profile-thumbnail" src="{{ profile.image }}" alt="" /></p>
              </div>
              <div class="profile-wrap">
                <p class="label-width">상태</p>
                <p>{{ profile.state }}</p>
              </div>
            </div>
          </div>
          <!-- //content -->
          {% if user == profile.user %}
            <div class="btn-group">
              <a href="{% url 'user:pf-update' %}" class="btn-modify">
                <span class="a11y-hidden">modify</span>
              </a>
            </div>
          {% endif %}
        </div>
      </section>
    </div>
  </div>
  <!-- //post view -->
{% endblock content %}
{% block script %}
<script>
  const form = document.querySelector(".profile-form")
  const get_image = form.querySelector("#get_image")

  let result = ""
  get_image.onchange = (event) => {
    const reader = new FileReader();
    reader.readAsDataURL(get_image.files[0]);
    reader.onload = function(e) {
      result = e.target.result
    }
  }
  
  form.addEventListener("submit", (event)=>{
    event.preventDefault()
    event.target.image.value = result
    form.submit()
  })
</script>
{% endblock script %}

user/templates/user/user_register.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/user_form.css' %}" />
{% endblock head %}

{% block content %}
<div class="view">
  <div class="max-width">
    <section class="wrap-box">
      <div class="inner">
        <div class="title-wrap">
          <h2>회원가입</h2>
        </div>
        <hr>
        <form class="user-form" action="{% url 'user:register' %}" method="post">
          {% csrf_token %}
          <div class="user-form-wrap">
            <label class="label-width" for="id_username">아이디</label>
            <p>{{ form.username }}</p>
          </div>
          {{ form.errors.username }}
          <div class="user-form-wrap">
            <label class="label-width" for="id_nickname">닉네임</label>
            <p>{{ form.nickname }}</p>
          </div>
          {{ form.errors.nickname }}
          <div class="user-form-wrap">
            <label class="label-width" for="id_password1">비밀번호</label>
            <p>{{ form.password1 }}</p>
          </div>
          {{ form.errors.password1 }}
          <div class="user-form-wrap">
            <label class="label-width" for="id_password2">비밀번호 확인</label>
            <p>{{ form.password2 }}</p>
          </div>
          {{ form.errors.password2 }}
          <input type="submit" class="button" value="회원가입">
        </form>
    </section>
  </div>
</div>
{% endblock content %}