blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 게시글
    path('', views.BlogIndex.as_view(), name='list'),
    path('write/', views.PostWrite.as_view(), name='write'),
    path('<int:post_id>/', views.PostDetail.as_view(), name='detail'),
    path('edit/<int:post_id>/', views.PostUpdate.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.PostDelete.as_view(), name='delete'),
    path('<int:post_id>/like/', views.PostLike.as_view(), name='like'),
    # 코멘트
    path('<int:post_id>/comment/write/', views.CommentWrite.as_view(), name='cm-write'),
    path('comment/delete/<int:comment_id>/', views.CommentDelete.as_view(), name='cm-delete'),
    path('<int:post_id>/<int:comment_id>/like/', views.CommentLike.as_view(), name='cm-like'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .admin_url import ADMIN_URL

urlpatterns = [
    # path('admin/', admin.site.urls),
    path(ADMIN_URL, admin.site.urls),
    path('', views.IndexMain.as_view()),
    path('error/', views.Error.as_view(), name='error'),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password/change/', views.PasswordChange.as_view(), name='pw-change'),
    path('delete/', views.UserDelete.as_view(), name='delete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('profile/update/', views.ProfileUpdate.as_view(), name="pf-update"),
]

templates/base.html
{% load static %}
{% load random_banner %}
<!DOCTYPE html>
<html lang="ko-KR">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>
      {{title}}
    </title>
		<!-- reset.css : meyerweb -->
		<link rel="stylesheet" href="{% static '/css/reset.css' %}" />
		<!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
		<link rel="stylesheet" href="{% static '/css/global.css' %}" />
		<!-- layout -->
		<link rel="stylesheet" href="{% static '/css/header.css' %}" />
		<link rel="stylesheet" href="{% static '/css/footer.css' %}" />
    <!-- component -->
    <link rel="stylesheet" href="{% static '/css/button.css' %}" />
    <link rel="stylesheet" href="{% static '/css/banner.css' %}" />
    <link rel="stylesheet" href="{% static '/css/category.css' %}" />
    <link rel="stylesheet" href="{% static '/css/author.css' %}" />
    {% block head %}
    {% endblock head %}
	</head>
	<body>
		<!-- header -->
		<header>
			<div class="max-width">
				<h1>
					<a href="{% url 'blog:list' %}">
						<img src="{% static '/assets/Logo.svg' %}" alt="Our Blog" />
					</a>
				</h1>
				<ul>
          {% if user.is_authenticated %}
            <!-- 로그인 -->
            <li class="profile-img">
              <a href="{% url 'user:pf-update' %}">
                <img src="{{ user.profile.image }}" alt="Profile Update" />
              </a>
            </li>
            <li>
              <a href="{% url 'blog:write' %}" class="button">
                <img src="{% static '/assets/icon-modify-white.svg' %}" alt="" />
                <span>Write</span>
              </a>
            </li>
            <li>
              <a href="{% url 'user:logout' %}" class="button white">
                <img src="{% static '/assets/icon-logout.svg' %}" alt="" />
                <span>Logout</span>
              </a>
            </li>
            <!-- //로그인 -->
          {% else %}
            <!-- 로그아웃 -->
            <li>
              <a href="{% url 'user:login' %}" class="button gray">
                <img src="{% static '/assets/icon-login.svg' %}" alt="" />
                <span>Login</span>
              </a>
            </li>
            <li class="only-pc">
              <a href="{% url 'user:register' %}" class="button gray">
                <img src="{% static '/assets/icon-register.svg' %}" alt="" />
                <span>Register</span>
              </a>
            </li>
            <!--// 로그아웃 -->
          {% endif %}
				</ul>
			</div>
		</header>
		<!--// header -->
    <!-- banner -->
    <div class="banner" image="{% random_banner %}">
      <div class="max-width">
        <div class="banner-contents">
          {% if banner %}
            <p class="sub-text">{{banner.sub}}</p>
            <p class="main-text">{{banner.main}}</p>
            <p class="description">
              {{banner.text}}
            </p>
          {% else %}
            <p class="sub-text">Python, Django, JavaScript & Life</p>
            <p class="main-text">Our Blog</p>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- //banner -->

    {% block content %}
    {% endblock content %}
    
		<!-- footer -->
		<footer>
			<div class="max-width">
				<h2>©Weniv Corp.</h2>
				<button class="top-button">TOP</button>
			</div>
		</footer>
		<!-- //footer -->
    <script src="{% static '/js/common_button.js' %}"></script>
    {% block script %}
    {% endblock script %}
	</body>
</html>

templates/error.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
  <link rel="stylesheet" href="{% static '/css/view.css' %}" />
{% endblock head %}
{% block content %}
  <!-- post view -->
  <div class="view">
    <div class="max-width">
      <section class="wrap-box">
        <div class="inner">
          <div class="title-wrap">
            <h2>정상적이지 않은 접근입니다.</h2>
          </div>
          <hr>
          <div class="view-contents">
            <p>존재하지 않는 페이지 이거나, 페이지에 접근할 권한이 없습니다.</p>
            <hr>
            <a class='button' href="{% url 'blog:list' %}">홈으로 이동</a>
          </div>
        </div>
      </section>
    </div>
  </div>
  <!-- //post view -->
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <!-- layout -->
  <link rel="stylesheet" href="{% static '/css/about.css' %}" />
  <!-- component -->
  <link rel="stylesheet" href="{% static '/css/main.css' %}" />
  <link rel="stylesheet" href="{% static '/css/index.css' %}" />
{% endblock head %}
{% block content %}
  <!-- main -->
  <main>  
    <div class="max-width">
      <article class="index max-width">
        <a class="button" href="{% url 'blog:list' %}">블로그로 입장하기</a>
      </article>
      <!-- about -->
      <aside class="about max-width">
        <h2>About Me</h2>
        <img src="{% static '/images/my_profile.png' %}" alt="" class="user-profile" />
        <p class="user-name">Kim Bareum</p>
        <p class="user-description">주니어 개발자 입니다.</p>
        <h3>Follow</h3>
        <ul class="sns">
          <li>
            <a href="https://github.com/kimbareum/OrmiMidProject1">
              <img src="{% static '/assets/Github.svg' %}" alt="GitHub" />
            </a>
          </li>
          <li>
            <a href="mailto:right.kim93@gmail.com">
              <img src="{% static '/assets/Mail.svg' %}" alt="mail" />
            </a>
          </li>
        </ul>
      </aside>
      <!-- //about -->
    </div>
  </main>
  <!-- //main -->
{% endblock content %}